

REMOTE_DATABASE_MONGO_URI = "mongodb://localhost:27017/"
TOPOLOGY_DATABASE_SYNC_INTERVAL_SECONDS = 10

LAYERS_MANAGER_BALANCER_FERNET_KEYS = [
    b"MVIwbyoflAwxZsz_joRFCxQBjHLr47K1mSxozN2Eq1c=",
    b"VeHBFxXZU3kK9Lq2yZ9XQYlVrsNscIwL3d9g4IjIZBA=",
    b"5lZ8rjWLlaKUeslVfi0XHiVkG9-68mNMBswJJv88VLo=",
]
